server:
  port: 8087
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      bindings:
        employeeRegistrationChannel:
          destination: employeeRegistrations
      default:
        contentType: application/json